spring.datasource.url=jdbc:postgresql://localhost:5433/library_db
spring.datasource.username=lib_admin
spring.datasource.password=lib_password
server.port=8081

# Automatically translates entity classes into database tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true